### ISSUE TITLE
.on('typewriteComplete', function() {} doesn't work

### ISSUE THREAD

**Issue by amityweb** [mrvautin/typewrite#7]
.on('typewriteComplete', function() {} doesn't work

Looking at your code, the settings.queue gets down to 4 when it finished, but the typewriteComplete requires it to be 0. So its not being called.

**Comment by ryanhanwu** [comment]
@amityweb It happens to me when my **select** action `to` is `from` + 1

PR created #8

**Comment by mrvautin** [comment]
Fixed in PR.
